### ISSUE TITLE
MSSQL scripts

### ISSUE THREAD

**Issue by Pmoshbr** [simse/chronos#13]
Hi I use a lot this docker to run scripts at my MSSQL database...
Everytime you update the docker I need to run this lines to be able to connect to this database with python... could add this to the master? This will help everyone that uses MSSQL databases... 

RUN pip install cython
RUN apk add --no-cache freetds-dev
RUN pip install pymssql

**Comment by simse** [comment]
This is a great idea, I have updated Docker image to include this
