### ISSUE TITLE
Cron expression unavailable

### ISSUE THREAD

**Issue by ShoGinn** [simse/chronos#14]
After the latest interface update, the cron expression is unavailable due to it looking for 1 number.

![Screenshot](https://i.imgur.com/ESM6MDV.png)

After saved:
![Screenshot](https://i.imgur.com/9Dt1SkR.png)

Looks like it shares the same format as interval:
![Screenshot](https://i.imgur.com/CHKV2ZT.png)

**Comment by simse** [comment]
Thanks for the report. This should be fixed in version `7375346` :)
