### ISSUE TITLE
Unable to Execute

### ISSUE THREAD

**Issue by mikedm139** [simse/chronos#15]
Running Version: 7375346 on unRAID 6.8.0 via Community Applications.
Set up simple `Hello World` as a test but when I press the `Execute` button, it raises an error.

```
stdout
/chronos/scripts/test/execute.sh: line 3: /chronos/scripts/test/.venv/bin/python: No such file or directory

stderr
no output.
```

Here is a screenshot of the setup of the test script.

![Test Script Setup](https://user-images.githubusercontent.com/277223/72658685-07549b00-397a-11ea-818d-31b037d006fc.png)

Here is a screenshot of the `/chronos/scripts/test/.venv/bin/` directory referenced by the error.

![/chronos/scripts/test/.venv/bin/](https://user-images.githubusercontent.com/277223/72658695-2e12d180-397a-11ea-82e2-2e621712b069.png)

and, in case it's relevant, a screenshot of the container template.
![Screen Shot 2020-01-17 at 10 41 29 PM](https://user-images.githubusercontent.com/277223/72658711-a1b4de80-397a-11ea-9a67-bef2052e283f.png)

**Comment by simse** [comment]
Does it also happen when you remove the shebang (#!/usr/bin/python3)?

**Comment by mikedm139** [comment]
Yes. The same error occurs when the entire script is:
```
print("Hello world!")
```

**Comment by mikedm139** [comment]
As a further test, I removed the extra path mapping from the docker template but the error remains the same.

**Comment by simse** [comment]
Such a strange issue.. Could you compress your entire chronos folder into a .zip or something similiar and send it to chronos@simse.io?

**Comment by simse** [comment]
Thank you for sending it to me. I'm not sure exactly what's going on. The fix right now would be to try removing and reinstalling the image.

**Comment by mikedm139** [comment]
Weird. I blew away the container, image and appdata folder. Reinstalled executed a quick `Hello World` test successfully. I could swear I had tried that already but it worked this time so I'll call it a win and close the issue.
