### ISSUE TITLE
Debug Python Scripts in Chronos

### ISSUE THREAD

**Issue by jaron-l** [simse/chronos#16]
Debugging python scripts that have run in chronos is a pain right now. I understand it's not meant to be a full IDE, but I think there are some basic things that could really make this a more powerful app. Some ideas that I think would really help:

1. Be able to kill or interrupt a running script
2. Live output of scripts
3. Terminal-like access

I realize that the third one would probably be the hardest but that would allow pdb debugging which would be a huge step towards being able to easily debug.

The reason I recommend this is that in my experience, you can't always perfectly replicate an environment for a script. When I am developing a script on my computer, I try to get as close as I can to replicating what it would look like for chronos, but eventually it's easier to just run it on chronos and see what happens. It would nice for some basic debugging functionality to help with that.

**Comment by simse** [comment]
Hello, you bring some valid points and good enhancement suggestions to the project.

But as you mentioned Chronos is not meant to be an IDE. Any project larger than a small script, should live in its own container. Should you wish to still run a larger script in Chronos and therefore need more advanced debugging, I'd recommend developing and testing using the same container that Chronos uses: python:3.8-buster.

**Comment by jaron-l** [comment]
That makes sense. Just an idea. Thanks for the tip.
