### ISSUE TITLE
Flask scripts not working properly

### ISSUE THREAD

**Issue by Daandeve** [simse/chronos#19]
Running
- unRAID 6.8.3
- lastest Chronos

When I run a flask script the web-ui is completely unresponsive, the flask server does run but I can't use the web-ui of Chronos...

**Comment by simse** [comment]
The only issue I can think of would be port collision. Have you tried running Flask with a different port? It should also be noted that Chronos isn't really meant to run Flask applications the way it's designed right now. That may change in the future.

**Comment by Daandeve** [comment]
I'am running Chronos on port 5000 and the flask app on 5050.
