### ISSUE TITLE
Adding a "Run on startup" script trigger

### ISSUE THREAD

**Issue by alonzoc1** [simse/chronos#20]
Hi, big fan of this project.

One feature I think might be helpful (especially in my use case) is a "Enable Run on Startup" trigger option. I have a couple scripts that I literally just need to run once my machine boots (and auto-starts docker), and occasionally run manually as needed. Currently I use this container to handle other scripts via cron expressions, and it'd be great to be able to consolidate scripts and include those that need to be run just once.

Let me know what you think, or if I missed this functionality!

**Comment by simse** [comment]
That's a great idea! I'll add this in next update.
