### ISSUE TITLE
Supporting this project

### ISSUE THREAD

**Issue by mullinmax** [simse/chronos#27]
Hey @simse this is a great project. Chronos is exactly what I've been looking for. How can I help support your efforts? I know enough to be dangerous with python but I am not very familiar with docker or web dev. I'd be more than happy to sponsor the repository or financially contribute if you'd be interested.

**Comment by simse** [comment]
You're always welcome to submit a pull request, but the code is a little messy at the moment, so it may be difficult at the moment. I am working on a way to accept donations, I'll let you know when it's ready. :)

**Comment by simse** [comment]
You can now sponsor me on Github if you're interested: https://github.com/sponsors/simse. Every little bit helps.
