### ISSUE TITLE
Save button

### ISSUE THREAD

**Issue by mullinmax** [simse/chronos#29]
It would be nice to have a save button rather than alerting the user of unsaved changes.

maybe use the unsaved changes when the user tried to navigate away?

**Comment by simse** [comment]
I hear you, where would you suggest placing the save button?

**Comment by bdelcamp** [comment]
> 
> 
> I hear you, where would you suggest placing the save button?

Maybe create it as a floating button along the bottom, or, change the checkmark next to the name in the list to a dick icon, or enable a save button next to the title of the script in the header portion of the editor, or add a static header bar when the document is dirty with save and revert options.

**Comment by mullinmax** [comment]
I might be late to the party but I was imagining just changing the "you have unsaved changes OK" msg to "save your changes OK" and have it not disappear. that would work for me.
