### ISSUE TITLE
Script triggers not executing

### ISSUE THREAD

**Issue by jfriend615** [simse/chronos#38]
Up until the latest update which brought the new UI, I had cron triggers working for a few scripts.

Since the update I haven't been able to get any triggers that will work. I've tried both interval and cron triggers and they aren't executing. Executing the script via the quick action button works as expected.

Any suggestions?

I'm running this on Unraid in a docker container.

Thanks!

**Comment by simse** [comment]
Could you share a .zip archive of your Chronos appdata folder?

**Comment by jfriend615** [comment]
Just sent an email to bug-reports@simse.io with my appdata folder attached.

**Comment by roblocksrocks** [comment]
Having the exact same issue here, running in docker on unRAID.  Unfortunately didn't get to test prior to current version but triggers are not working for current version.

**Comment by simse** [comment]
@jfriend615 Could you try a clean install by deleting your Chronos appdata folder, and test whether that fixed the issue?

**Comment by simse** [comment]
@roblocksrocks Could you also send your Chronos appdata folder to me? The email is bug-reports@simse.io

**Comment by jfriend615** [comment]
@simse Tried a clean install of Chronos, able to run scripts manually but neither the Cron or Interval Trigger's are working.

**Comment by roblocksrocks** [comment]
@simse I sent over the folder.

**Comment by horphi0815** [comment]
@simse hi ihave the same issue. Clean docker and no trigger execution. Unraid 6.8.3

**Comment by simse** [comment]
I have just released version 0.2, **that prevents malformed CRON expressions from silently crashing the program**. If you are still having problems with your CRON triggers please check your logs for errors. Notably ?s in expressions are not supported. If it's still not working, please send a .zip archive of your Chronos folder to bug-reports@simse.io.

**Comment by jfriend615** [comment]
Thanks, @simse. After updating I'm now able to use the interval triggers.

**Comment by jfriend615** [comment]
Thanks, after updating I'm now able to use the interval triggers. Is there a plan to support "?" in cron expressions?

I'm not too familiar with CRON Expressions, just enough to be dangerous with them, but is there any way to write them without "?"s?
