### ISSUE TITLE
[Request] Ability to clone remote repository

### ISSUE THREAD

**Issue by debaser19** [simse/chronos#45]
Hey there, love Chronos btw, thanks for all your work!

I've got a few different scripts I run that I make somewhat frequent updates on. It'd be handy to have an option to pull the script down from the git repo (github or bitbucket specifically) to pull the changes down. Maybe even an option to pull changes down if it sees a new commit on the repo?

Thanks!

**Comment by simse** [comment]
Greta idea. As soon I have some more time on my hands, I'll definitely look into this.
