### ISSUE TITLE
[Feature Request] Run scripts with arguments

### ISSUE THREAD

**Issue by rg9400** [simse/chronos#47]
I stumbled onto this project, and I think it could be very useful. Can you add the ability to execute scripts with arguments? The usecase is that I might want to run a script with different arguments at different time intervals. Right now, I need to modify the script, hardcode the argument values, and create multiple versions to manage this task.

In my opinion, the arguments should be attached to the intervals for execution as well as the ad-hoc execute option. Attaching them to the script requires multiple versions of the same script.

**Comment by angrycuban13** [comment]
This would be a great addition to this awesome little application.

**Comment by shiner66** [comment]
Is that request dead or dev is working on it?

**Comment by angrycuban13** [comment]
This project has not been worked on in nearly 2 years. I wouldn't hold my breath
