### ISSUE TITLE
Script to stop another script

### ISSUE THREAD

**Issue by droopified** [simse/chronos#48]
Is possible to stop another a executed script? I have a script that is running on a loop and it waits for data and if the data is there it will run a discord bot, the problem is, the discord bot stays executed and won't run or I just can't figure out how to run stuff in the background of the bot but I was thinking a different script and kill that discord bot. Would you be possible?

**Comment by simse** [comment]
Chronos is designed exclusively for scripts that do not run indefinitely. Chronos is therefore not suited for Discord bots. I would instead recommend creating your own Dockerimage for this purpose. You can find out more here: https://hub.docker.com/r/gorialis/discord.py
