### ISSUE TITLE
Feature: Reference a path to script (instead of embedding it in chronos)

### ISSUE THREAD

**Issue by sinaxin** [simse/chronos#56]
I am using Chronos (container) in Unraid. I have a share (scripts) that I pass as a directory path to the container, and would like to use Chronos to manage the execution of the scripts contained in that directory.

Suggestion: having a toggle button to chose between writing the script directly in Chronos OR reference a script path (it could be manually in a textbox or browse the filesystem)

Thanks!

**Comment by simse** [comment]
I'm sorry, Chronos is no longer receiving any updates.
