### ISSUE TITLE
No such file or directory error after update

### ISSUE THREAD

**Issue by Mattyfaz** [simse/chronos#7]
Hey!
I updated a few days ago and none of my scripts appear to run anymore, all report the following error:

`/chronos/scripts/scriptName/execute.sh: line 3: /chronos/scripts/scriptName/.venv/bin/python: No such file or directory`

Is there something I now need to change/fix? All directories seem correct and I can see the file existing when I browse to it, I didn't change anything aside from updating the container.

![image](https://user-images.githubusercontent.com/10377148/70800232-d247ac80-1dff-11ea-9262-fef08bf38640.png)

![image](https://user-images.githubusercontent.com/10377148/70800241-d5db3380-1dff-11ea-9853-2dcca11b36e6.png)

![image](https://user-images.githubusercontent.com/10377148/70800496-89dcbe80-1e00-11ea-97bf-adb54c5c8cd7.png)

**Comment by simse** [comment]
Hi Matt, I'm sorry to hear this. Could try making a new script and see if the problem persists?

**Comment by Mattyfaz** [comment]
Hi Simse, deleting it and adding it again seems to have done the trick! Thank you!

**Comment by simse** [comment]
Strange indeed. Glad to hear it's working again!

**Comment by sbarb** [comment]
Hi, this issue happens to me every update. I'm running a dockerized container
