### ISSUE TITLE
Python Logging module (won't output to logs)

### ISSUE THREAD

**Issue by ShoGinn** [simse/chronos#8]
I have been using this as a neat way to run one of my modules.

In my module I use the python logging handler. (https://docs.python.org/3/library/logging.handlers.html#module-logging.handlers)
More specifically the SteamHandler. It uses sys.stderr by default.

I was trying to figure out why my console logs were not getting added to the output when I found this reference:
https://stackoverflow.com/questions/6098327/program-called-with-subprocess-logger-messages-are-not-printed

Upon investigating your code
https://github.com/simse/chronos/blob/0af2c3369e222e8e8c93194ffa100a3a13236607/chronos/script.py#L125-L128

I am not as familiar using subprocess but can you just check if those are empty and output the text appropriately?

````
        # Check if it errored or was successful
        process_output = output + error
````

Obviously my quick code can be made better ;)

**Comment by simse** [comment]
I see what you mean. I will push a temporary fix as soon as possible.

**Comment by ShoGinn** [comment]
Works great!
